dependencies:
  conda-forge:
  - python=3.11.11
  - uv=0.6.11
  pypi:
  - sema4ai-actions=1.3.11
  - pydantic=2.11.4
description: Custom actions for extracting and processing invoice data from PDFs
dev-dependencies:
  conda-forge:
  - pytest=8.3.5
dev-tasks:
  test: pytest tests -rfE -vv
name: InvoiceExtractor
packaging:
  exclude:
  - ./.git/**
  - ./.vscode/**
  - ./devdata/**
  - ./output/**
  - ./venv/**
  - ./.venv/**
  - ./.DS_Store/**
  - ./**/*.pyc
  - ./**/*.zip
pythonpath:
- src
- tests
spec-version: v2
version: 0.0.1
